options:
  version:
    type: string
    default: "https://storage.googleapis.com/golang/go1.10.linux-amd64.tar.gz"
    description: "Url to Go binary release. Changing this after initial install has no effect."
